version: '3'
services:
  foundryvtt:
    image: lichtobergo/fvtt-docker:latest
    container_name: fvtt
    volumes:
      - /path/to/your/foundry/data/directory:/data/foundryvtt
      - /path/to/your/foundry/zip/file:/host
      - /path/to/your/foundry/app/file:/opt/foundryvtt/resources/app
    restart: unless-stopped
